### ISSUE TITLE
dr2_logger.spec

### ISSUE THREAD

**Issue by maxbechtold** [ErlerPhilipp/dr2_logger#2]
I was wondering how the executable is built with PyInstaller. The README.md mentions a dr2_logger.spec, yet I don't find it on the master branch. Did it get lost?

**Comment by ErlerPhilipp** [comment]
You are right. I forgot that it was ignored. 
You'll need to change a path in that file before you can use it with pyinstaller. Also, it will need an installed compiler, e.g. the Visual Studio compiler on Windows.

Please tell me how it works out.

**Comment by ErlerPhilipp** [comment]
i checked my steps for building again. the dr2_logger.spec was ignored correctly.
you need to call "pyinstaller dr2_logger.py" and it will create the .spec file and then build the executable. i'll update the readme soon.
