### ISSUE TITLE
Building dr2_logger in a Windows venv

### ISSUE THREAD

**Issue by maxbechtold** [ErlerPhilipp/dr2_logger#3]
So I'm following the build steps in README, but it's not self explanatory when it gets to the `basemap` dependency.  [The GitHub docs](https://github.com/matplotlib/basemap#install) describe a way to do it with pip, but basemap expects the GEOS engine to be setup already. It seems I need to manually download and compile the GEOS engine... and my Windows is not equipped for that.

Can you give some hints on how to simplify this part, perhaps even a script?

**Comment by ErlerPhilipp** [comment]
Please try installing basemap via conda:
conda install -c anaconda basemap 
if necessary: conda install -c conda-forge geos

I'm currently checking the requirements and will provide a yml for easier setup of conda environments. But ran into a QT DLL issue. I'll keep you updated.

**Comment by ErlerPhilipp** [comment]
I pushed a dr2logger.yml to the master branch. Please follow the instructions in the readme (section "Run and Build") to get exactly the right versions of the required packages. 

I hope I didn't forget anything. The versions of QT (via conda) and PyInstaller (via pip) are probably critical. Basemap and GEOS should not be necessary anymore.

Does it work for you now?

**Comment by maxbechtold** [comment]
Thanks for the docs, but I missed that I a need a data science platform for this to run... which I don't want to set up just now, sorry. But it looks like the build is more automated now. 
You might want to consider a CI build like GitHub Actions (have a look at how dirt-rally-time-recorder is built), which provide both Windows and Linux runners. This will also tell if the Windows built works properly.
